<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[chrome launched]]>
    </line>
    <line>
      <![CDATA[chrome launched]]>
    </line>
    <line>
      <![CDATA[chrome launched]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="108082" started-at="2021-07-02T11:16:55 IST" finished-at="2021-07-02T11:18:43 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="108082" started-at="2021-07-02T11:16:55 IST" finished-at="2021-07-02T11:18:43 IST">
      <class name="com.crypto.scripts.LoginTest">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="preCondition" is-config="true" duration-ms="11603" started-at="2021-07-02T11:16:56 IST" finished-at="2021-07-02T11:17:08 IST">
          <reporter-output>
            <line>
              <![CDATA[chrome launched]]>
            </line>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="setup" is-config="true" duration-ms="62" started-at="2021-07-02T11:17:08 IST" finished-at="2021-07-02T11:17:08 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="logincheck(java.lang.String, java.lang.String)[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="logincheck" duration-ms="24412" started-at="2021-07-02T11:17:08 IST" data-provider="Logindetails" finished-at="2021-07-02T11:17:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test01]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sasadas]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crypto.scripts.LoginTest.logincheck(LoginTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincheck -->
        <test-method status="PASS" signature="postCondition()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="postCondition" is-config="true" duration-ms="752" started-at="2021-07-02T11:17:32 IST" finished-at="2021-07-02T11:17:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondition()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="preCondition" is-config="true" duration-ms="10095" started-at="2021-07-02T11:17:33 IST" finished-at="2021-07-02T11:17:43 IST">
          <reporter-output>
            <line>
              <![CDATA[chrome launched]]>
            </line>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="setup" is-config="true" duration-ms="1" started-at="2021-07-02T11:17:43 IST" finished-at="2021-07-02T11:17:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="logincheck(java.lang.String, java.lang.String)[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="logincheck" duration-ms="24381" started-at="2021-07-02T11:17:43 IST" data-provider="Logindetails" finished-at="2021-07-02T11:18:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test02]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sasadas]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crypto.scripts.LoginTest.logincheck(LoginTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincheck -->
        <test-method status="PASS" signature="postCondition()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="postCondition" is-config="true" duration-ms="749" started-at="2021-07-02T11:18:07 IST" finished-at="2021-07-02T11:18:08 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondition()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="preCondition" is-config="true" duration-ms="9570" started-at="2021-07-02T11:18:08 IST" finished-at="2021-07-02T11:18:18 IST">
          <reporter-output>
            <line>
              <![CDATA[chrome launched]]>
            </line>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="setup" is-config="true" duration-ms="2" started-at="2021-07-02T11:18:18 IST" finished-at="2021-07-02T11:18:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="logincheck(java.lang.String, java.lang.String)[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="logincheck" duration-ms="24381" started-at="2021-07-02T11:18:18 IST" data-provider="Logindetails" finished-at="2021-07-02T11:18:42 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test03]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sasadas]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crypto.scripts.LoginTest.logincheck(LoginTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincheck -->
        <test-method status="PASS" signature="postCondition()[pri:0, instance:com.crypto.scripts.LoginTest@5d76b067]" name="postCondition" is-config="true" duration-ms="733" started-at="2021-07-02T11:18:42 IST" finished-at="2021-07-02T11:18:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- com.crypto.scripts.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
